fixup

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -18,7 +18,9 @@ jobs:
         vmImage: 'ubuntu-16.04'
         CPU: amd64
       Linux_i386:
-        vmImage: 'ubuntu-16.04'
+        # bug #17325: fails on 'ubuntu-16.04' because it now errors with:
+        # g++-multilib : Depends: gcc-multilib (>= 4:5.3.1-1ubuntu1) but it is not going to be installed
+        vmImage: 'ubuntu-18.04'
         CPU: i386
       OSX_amd64:
         vmImage: 'macOS-10.15'
@@ -64,6 +66,7 @@ jobs:
       displayName: 'Install node.js 12.x'
 
     - bash: |
+        set -e
         sudo apt-fast update -qq
         DEBIAN_FRONTEND='noninteractive' \
           sudo apt-fast install --no-install-recommends -yq \
@@ -72,21 +75,28 @@ jobs:
       condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['CPU'], 'amd64'))
 
     - bash: |
-        sudo dpkg --add-architecture i386
+        set -e
+        . ci/funs.sh
+        echo_run sudo dpkg --add-architecture i386
+        echo_run echo ok1
+        echo_run echo ok2
+        echo_run echo nonexistand_asdf
+        echo_run echo ok3
 
         # Downgrade llvm:
         # - llvm has to be downgraded to have 32bit version installed for sfml.
+
         cat << EOF | sudo tee /etc/apt/preferences.d/pin-to-rel
         Package: libllvm6.0
         Pin: origin "azure.archive.ubuntu.com"
         Pin-Priority: 1001
         EOF
 
-        sudo apt-fast update -qq
+        echo_run sudo apt-fast update -qq
         # `:i386` (e.g. in `libffi-dev:i386`) is needed otherwise you may get:
         # `could not load: libffi.so` during dynamic loading.
         DEBIAN_FRONTEND='noninteractive' \
-          sudo apt-fast install --no-install-recommends --allow-downgrades -yq \
+          echo_run sudo apt-fast install --no-install-recommends --allow-downgrades -yq \
             g++-multilib gcc-multilib libcurl4-openssl-dev:i386 libgc-dev:i386 \
             libsdl1.2-dev:i386 libsfml-dev:i386 libglib2.0-dev:i386 libffi-dev:i386
 
@@ -95,14 +105,15 @@ jobs:
 
         exec $(which gcc) -m32 "\$@"
         EOF
+
         cat << EOF > bin/g++
         #!/bin/bash
 
         exec $(which g++) -m32 "\$@"
         EOF
 
-        chmod 755 bin/gcc
-        chmod 755 bin/g++
+        echo_run chmod 755 bin/gcc
+        echo_run chmod 755 bin/g++
 
       displayName: 'Install dependencies (i386 Linux)'
       condition: and(eq(variables['Agent.OS'], 'Linux'), eq(variables['CPU'], 'i386'))
@@ -112,6 +123,7 @@ jobs:
       condition: eq(variables['Agent.OS'], 'Darwin')
 
     - bash: |
+        set -e
         mkdir dist
         curl -L https://nim-lang.org/download/mingw64.7z -o dist/mingw64.7z
         curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
@@ -126,6 +138,7 @@ jobs:
       displayName: 'Add build binaries to PATH'
 
     - bash: |
+        set -e
         echo 'PATH:' "$PATH"
         echo '##[section]gcc version'
         gcc -v
@@ -145,6 +158,7 @@ jobs:
       displayName: 'Restore built csources'
 
     - bash: |
+        set -e
         ncpu=
         ext=
         case '$(Agent.OS)' in
