handling of compiler procs improved for DLL generation

diff --git a/tools/buildsh.tmpl b/tools/buildsh.tmpl
--- a/tools/buildsh.tmpl
+++ b/tools/buildsh.tmpl
@@ -1,5 +1,5 @@
 #! stdtmpl(subsChar='?') | standard
-#proc GenerateBuildScript(c: TConfigData): string = 
+#proc GenerateBuildShellScript(c: TConfigData): string = 
 #  result = "#! /bin/sh\n# Generated by niminst\n"
 CC="gcc"
 LINKER="gcc"
@@ -83,7 +83,15 @@ case $myos in
     $LINKER $LINK_FLAGS -o ?{c.binPaths[0]}/?{toLower(c.name)} ?linkCmd || exit 1
     ;;
 #    end for
+  *)
+    echo "Error: no C code generated for: [$myos: $mycpu]"
+    exit 1
+    ;;
   esac
+  ;;
+*) 
+  echo "Error: no C code generated for: [$myos: $mycpu]"
+  exit 1
   ;;
 #  end for
 esac
