Resolved conflict in buildsh.tmpl

diff --git a/tools/niminst/buildsh.tmpl b/tools/niminst/buildsh.tmpl
--- a/tools/niminst/buildsh.tmpl
+++ b/tools/niminst/buildsh.tmpl
@@ -153,8 +153,18 @@ case $ucpu in
   *power*|*ppc* )
     mycpu="powerpc" ;;
   *mips* )
-    mycpu="mips" ;;
-  *arm*|*armv6l*|*armv71* )
+    mycpu="$("$CC" -dumpmachine | sed 's/-.*//')"
+    case $mycpu in
+      mips|mipsel|mips64|mips64el)
+        ;;
+      *)
+        echo 2>&1 "Error: unknown MIPS target: $mycpu"
+        exit 1
+    esac
+    ;;
+  *arm*|*armv6l* )
+    mycpu="arm" ;;
+  *armv71* )
     mycpu="arm" ;;
   *aarch64* )
     mycpu="arm64" ;;
