build.sh: Output error messages to stderr
Just in case we are running this in some CI.

diff --git a/tools/niminst/buildsh.tmpl b/tools/niminst/buildsh.tmpl
--- a/tools/niminst/buildsh.tmpl
+++ b/tools/niminst/buildsh.tmpl
@@ -18,7 +18,7 @@ do
       break;
       ;;
     -*)
-      echo "Error: Unknown option: $1" >&2
+      echo 2>&1 "Error: Unknown option: $1" >&2
       exit 1
       ;;
     *)  # No more options
@@ -94,7 +94,7 @@ case $uos in
     myos="haiku"
     ;;
   *) 
-    echo "Error: unknown operating system: $uos"
+    echo 2>&1 "Error: unknown operating system: $uos"
     exit 1
     ;;
 esac
@@ -119,7 +119,7 @@ case $ucpu in
   *arm*|*armv6l* )
     mycpu="arm" ;;
   *) 
-    echo "Error: unknown processor: $ucpu"
+    echo 2>&1 "Error: unknown processor: $ucpu"
     exit 1
     ;;
 esac
@@ -143,14 +143,14 @@ case $myos in
     ;;
 #    end for
   *)
-    echo "Error: no C code generated for: [$myos: $mycpu]"
+    echo 2>&1 "Error: no C code generated for: [$myos: $mycpu]"
     exit 1
     ;;
   esac
   ;;
 #  end for
 *) 
-  echo "Error: no C code generated for: [$myos: $mycpu]"
+  echo 2>&1 "Error: no C code generated for: [$myos: $mycpu]"
   exit 1
   ;;
 esac
